### ISSUE TITLE
Translating modulate function from ImageMagick to Libvips.

### ISSUE THREAD

**Issue by alexandrearc** [janko/image_processing#102]
Hey guys,

I have this piece of code using ImageMagick that I want to convert to Libvips but i am not sure how to achieve the same behaviour as the modulate function:

`ImageProcessing::MiniMagick
      .source(img)
      .colorspace(:srgb)
      .convert('jpeg')
      .modulate('120,10,100')
      .fill('#222b6d')`

Basically I am not sure how to adjust brightness, saturation and hue using Libvips. I couldn't find it in the documentation.

Thanks,
Alex

**Comment by janko** [comment]
Questions about converting ImageMagick commands to libvips are probably best asked at [ruby-vips discussions](https://github.com/libvips/ruby-vips/discussions), the author is usually quick to provide the equivalent libvips command. In this case, the ImageMagick command to convert is:

```sh
magick source.png -colorspace srgb -modulate '120,10,10' -fill '#222b6d' destination.jpeg
```

**Comment by alexandrearc** [comment]
Sure @janko thanks!
