### ISSUE TITLE
Adding white background while converting from `png` to `jpg` with `resize_and_pad!` fails with linear issue

### ISSUE THREAD

**Issue by GabrielLyonB** [janko/image_processing#106]
Hi there 👋 ,

I'm trying to convert a `.png` file (without background) to a `jpg` using `.resize_and_pad!` and i keep getting this error:
```
Vips::Error: linear: vector must have 1 or 4 elements
```
This is my code:
``` ruby
vips = ImageProcessing::Vips.source(file_path)
new_file_path = vips.convert('jpg').resize_and_pad!(400, 400, alpha: true, background: [255, 255, 255])
```
Am i doing something wrong?
I have tried adding the `linear: true` option but i get the same error. 
Appreciate any help.

**Comment by janko** [comment]
Because you've enabled the alpha channel, the background color probably also needs to include the alpha channel (a fourth element). I believe it's a decimal number from 0 to 1, but I could be wrong.

**Comment by GabrielLyonB** [comment]
Thank you @janko. Adding a fourth value did fix the error. Although it had to use `[255, 255, 255, 255]` to obtain a white backround (for the remaining area).
I want to add that i got the error with or without `alpha: true` parameter.

I have a another question now, for what i've seen in this [file](https://github.com/janko/image_processing/blob/52d5126fdead23e8702400db6b2717da25c06faf/lib/image_processing/vips.rb#L85) the background option is only for the remaining area. Is there a way to change the background color of the image it self?

**Comment by janko** [comment]
> I want to add that i got the error with or without alpha: true parameter.

I'm not sure why is that 🤔 

> I have a another question now, for what i've seen in this [file](https://github.com/janko/image_processing/blob/52d5126fdead23e8702400db6b2717da25c06faf/lib/image_processing/vips.rb#L85) the background option is only for the remaining area. Is there a way to change the background color of the image it self?

That would require the imaging library to know what is a background in an image, and I'm not sure libvips is capable of that, though it could be. I'm not experienced in image processing, so your best bet is to search the internet or ask the libvips author.

I will close this issue, as the background color requiring an alpha channel seems to be related only to ruby-vips, not image_processing.

**Comment by GabrielLyonB** [comment]
Only if it helps anybody else,
> I have a another question now, for what i've seen in this [file](https://github.com/janko/image_processing/blob/52d5126fdead23e8702400db6b2717da25c06faf/lib/image_processing/vips.rb#L85) the background option is only for the remaining area. Is there a way to change the background color of the image it self?

The `background` option in `resize_and_pad` only adds background to remaining area of the image. If you are trying to add a background color for a `png` transparent you have to use the [`saver`](https://github.com/janko/image_processing/blob/master/doc/vips.md#saver) method with a `background` option that will be passed to the vips `write_to_file` method.
Here is the [issue](https://github.com/libvips/ruby-vips/issues/348) i opened in vips library that make me realize my mistake.
