### ISSUE TITLE
Default appears to be ruby-vips rather than mini_magick - Rails 7, Ruby 3

### ISSUE THREAD

**Issue by clarkology56** [janko/image_processing#109]
**Issue / context:**
I tried creating an image variant and it did not work. Then I started to notice that when I run tests (using mini-test), I was getting about 80 lines of ruby-vips warnings. I thought this was strange because I thought the default was mini_magick. 

I tried setting the default manually in `config/application.rb` by adding  `config.active_storage.variant_processor = :mini_magick` but it made no difference. 

**Expectation:** 
Image variants work and when running tests, there would be no ruby-vips warnings

**Actual:**
Image variants do not work and when running tests, there are no ruby-vips warnings

**Fix / workaround:**
I added `config.active_storage.variant_processor = :mini_magick` to each of my environment files, it fixed my issues (the ruby-vips warnings went away when running tests and my image variants started working):
`config/environments/test.rb`
`config/environments/development.rb`
`config/environments/staging.rb`
`config/environments/production.rb`

**Versions**
I am using Ruby 3 and Rails 7

```
ruby '3.1.2'
gem 'rails', '~> 7.0.4'
gem 'image_processing', '~> 1.2'
```

**Comment by janko** [comment]
This is expected, Active Storage uses the vips processor by default. It used to use MiniMagick in earlier versions, but it switched to using vips by default in Rails 7.0.

**Comment by clarkology56** [comment]
Ah, makes sense. Thank you so much @janko!
