### ISSUE TITLE
WARNING: The convert command is deprecated in IMv7, use "magick"

### ISSUE THREAD

**Issue by doutatsu** [janko/image_processing#123]
It looks like this has been deprecated, no need to run `magick convert`, but should simply be `magick` now. 

https://github.com/ImageMagick/ImageMagick/discussions/7366#discussioncomment-9645349

**Comment by janko** [comment]
Thanks, there is already and open issue on MiniMagick repo. The only thing that made me reluctant to release it right way is that I don't know how much `magick` is compatible with `magick convert`. So, I pushed the change to MiniMagick master branch to leave some time for testing before I release it.

**Comment by janko** [comment]
I just released MiniMagick 4.13.0 that silencees this warning (see https://github.com/minimagick/minimagick/issues/560). I decided to switch from `magick convert` to `magick` in the next major version of MiniMagick, and this will probably be followed up by a major version of ImageProcessing gem.
