### ISSUE TITLE
Undefined method "get_construct_args"

### ISSUE THREAD

**Issue by konung** [janko/image_processing#131]
Hi. 

I actually discovered a bug related to minimagick 5.0 support mentioned in issue #125 

I updated image_processing  to 1.13 and ran into an error 

```ruby
# Just processing a PDF attachment in my model 

model = Label.last
model.original_file.representation(resize_to_limit: [100, 100]).processed

NoMethodError: undefined method `get_construct_args' for #<Vips::Operation:0x000000012a3dfba0 @ptr=#<FFI::Pointer address=0x0000600000a19f80>, @struct=#<Vips::Operation::ManagedStruct:0x000000012a3df808>, @references=[]>
from /Users/konung/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/image_processing-0.11.2/lib/image_processing/vips.rb:105:in `select_valid_options'

```

Downgrading to 1.12.2 resolved the issue. 

The error is a bit cryptic, as it's pointing to Vips, when it seems that Minimagick support is the cause ( I think?) . Still haven't figured out the true root cause. Just thought it bring it up here.

**Comment by janko** [comment]
Active Storage is using the libvips backend here (it's the default), so this is unrelated to MiniMagick. I don't know at the moment what caused this apparent regression, I will take a look.

**Comment by janko** [comment]
You said you upgraded ImageProcessing to 1.13.0, but the stack trace shows version 0.11.2, which is ancient. So, that's likely the root cause of the error.

If you're still experiencing it with the most recent version, please post a self-contained example that reproduces the issue (without Active Storage), and then we can re-open.

**Comment by TravelingTice** [comment]
Also stumbled into this issue and was also mistakenly on version 0.11.2.. even though I just added `gem 'image_processing'` to my Gemfile... apparently we need to specify `, '~> 1.12'` should be used?

**Comment by janko** [comment]
Not sure if something else is depending on a lower version of MiniMagick or ruby-vips, which might make Bundler prefer versions of ImageProcessing that didn't have them as dependencies.
