### ISSUE TITLE
Sharing Libvips & AWS Lambda Work

### ISSUE THREAD

**Issue by metaskills** [janko/image_processing#50]
First, thanks so much for the work here and making it easy to use either ImageMagick or Libvips with Ruby. I wanted to share my Lambda Layer work that makes it easy to use `ImageProcessing::Vips` with AWS Lambda via the ruby-vips gem.

https://github.com/customink/ruby-vips-lambda

A little related to #32 maybe, especially if people are interested in moving off Heroku to AWS Lambda via something like the Lamby gem. https://github.com/customink/lamby

**Comment by hmistry** [comment]
Thanks for sharing that with us. It's great to see a ruby-vips-lambda project. In a past project, I used Vips on lambda with sharp (js library) as there was no ruby support back then. So if I follow correctly, the ruby-vips-lambda has to be used with lamby to build an api to process the images right?

**Comment by metaskills** [comment]
If your application has enough complexity that the conventions of Rails warrants, most do IMO, then yes. Lamby can be a huge help to simply bolt your existing (or new) Rails app to the Lambda handler. That said, if your Lambda "app" I simple, you could always go with basic Ruby POROs. For example, here is a demo project using SAM and basic Ruby I did for our user group. https://github.com/757rb/hello-757rb-lambda

**Comment by janko** [comment]
Thanks for letting us know. Perhaps it would be nice to add it to the [ruby-vips wiki](https://github.com/libvips/ruby-vips/wiki).
