### ISSUE TITLE
Carrierwave Configuration

### ISSUE THREAD

**Issue by lws68825** [janko/image_processing#58]
Hi @janko,
I notice that carrierwave depends on image_processing. How to configure carrierwave to process images with libvips?
Thank you!

**Comment by janko** [comment]
While the `CarrierWave::MiniMagick` module was rewritten to use `ImageProcessing::MiniMagick`, it's still MiniMagick-specific. You'd need to write a separate implementation for libvips. I've tried to rewrite [carrierwave-vips](https://github.com/eltiare/carrierwave-vips) to use ImageProcessing, but the PR was [rejected](https://github.com/eltiare/carrierwave-vips/pull/29).
