### ISSUE TITLE
How to recover from 500 Error when resize_to_fit is incapable of completing?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [janko/image_processing#59]
Hello @janko and team!

I've been trying to navigate around a 500 Server Error but I'm now crying uncle and need to call in the big guns for direction :)

When an image is uploaded, I pass it through a series of a `.resize_to_fit` commands to generate several different sizes. Depending on the dimensions of the image being passed in, there are times when the smallest size returns the following Vips error:

`Vips::Error - shrinkv: image has shrunk to nothing`

I understand why this happening and I think Vips is right to issue the complaint, but my question is

**how do "recover" from this error being returned? Is there a way I can run some sort of "check" prior to execution?**

I've tried using the `.valid_image?` method, but that doesn't seem to be what I'm after (either that, or I'm not using it properly).

Here is the method I'm currently using, the offending `resize_to_fit().call` is the `size_5` version as shown below:

```
def generate_thumbnails(file)
  pipeline = ImageProcessing::Vips
  size 1200 = pipeline.source(file).resize_to_fit(1200, 1200).call
  size 400 = pipeline.source(size_1200).resize_to_fit(400, 400).call
  size 200 = pipeline.source(size_400).resize_to_fit(200, 200).call
  size 125 = pipeline.source(size_200).resize_to_fit(125, 125).call 
  size 75 = pipeline.source(size_125).resize_to_fit(75, 75).call
  size 50 = pipeline.source(size_75).resize_to_fit(50, 50).call
  size 5 = pipeline.source(size_50).resize_to_fit(5, 5).call

  {  large: size_1200, 
     medium: size_400,
     thumb: size_200,
     small_thumb: size_125,
     small: size_75,
     mini: size_50,
     speck: size_5 }
end

```
For example, my initial thought is that if the smallest size is a no-go, then simply don't try to do it and assign the previous "size_50/mini" version instead. And then, in the view, I'll just visually shrink down the "now too large" speck version to the desired 5x5 size with the usual HTML/CSS/JS combo.

Thank you in advance for your help! Please let me know if there is any more information you need from my end!

-Blake

**Comment by janko** [comment]
Hi 👋 Is there any downside with just trying to run that process operation and handling the potential exception?

```rb
def generate_thumbnails(file)
  pipeline = ImageProcessing::Vips
  size 1200 = pipeline.source(file).resize_to_fit(1200, 1200).call
  size 400 = pipeline.source(size_1200).resize_to_fit(400, 400).call
  size 200 = pipeline.source(size_400).resize_to_fit(200, 200).call
  size 125 = pipeline.source(size_200).resize_to_fit(125, 125).call 
  size 75 = pipeline.source(size_125).resize_to_fit(75, 75).call
  size 50 = pipeline.source(size_75).resize_to_fit(50, 50).call
  begin
    size 5 = pipeline.source(size_50).resize_to_fit(5, 5).call
  rescue Vips::Error
    size 5 = size_50
  end

  # ...
end
```

**Comment by Blake-LeBlanc** [comment]
Thank you @janko, that's just what I was looking for! 

I was trying to use `rescue_from` at the controller level, was not aware of `rescue` from within the uploader. 

I really appreciate your excellent support, thank you for getting back to me so quickly!
