### ISSUE TITLE
unified api

### ISSUE THREAD

**Issue by MichaelSp** [janko/image_processing#61]
Wouldn't it be awesome if there is just one API and it automatically chooses the best implementation depending on the task at hand?

Feel free to close if you don't like the idea

**Comment by janko** [comment]
Could you expand on this idea? What do you mean exactly by "choosing the best implementation"?

**Comment by MichaelSp** [comment]
"best" == fastest

where fastest could be automatically detected based on some integration test and would be persisted in the gem.

**Comment by janko** [comment]
In my experience, it's not really that libvips is faster in some things, and ImageMagick is faster in other – libvips is generally faster than ImageMagick in everything, and with lower memory usage.

As far as I'm concerned, the only reason to use ImageMagick is a wider range of existing "how to" StackOverflow answers and easier installation on different platforms (e.g. on Heroku it comes installed by default). Though I admit I haven't had to do more advanced image processing myself, so maybe I'm not seeing some obvious limitations in libvips yet.

Note that ImageMagick and libvips also have widely different APIs and options (which are supported by ImageProcessing), so auto-switching between the two would probably lead to confusing behaviour anyway 😉
