### ISSUE TITLE
representations show (Vips::Error) "VipsOperation: class \"auto_orient\" not found"

### ISSUE THREAD

**Issue by ck2000** [janko/image_processing#65]
Env on OSX:
brew install vips --> vips version 8.9.1
if I am using variant with auto_orient true I get the VipsOperation: class \"auto_orient\" not found error.

`photo.variant(auto_orient: true, gravity: "center", resize: "30x30^", crop: "30x30+0+0")`

From my tests the bug appreas since vips version 8.7+

**Comment by janko** [comment]
`:auto_orient` is not a valid libvips option, nor is `:gravity` or `:crop` with a geometry string. If you want to use libvips, you need to use libvips equivalents, consult the [documentation](https://github.com/janko/image_processing/blob/master/doc/vips.md#readme) for that.
