### ISSUE TITLE
False positive "Source format is multi-layer, but destination format is single-layer."

### ISSUE THREAD

**Issue by Kukunin** [janko/image_processing#66]
I receive `ImageProcessing::Error: Source format is multi-layer, but destination format is single-layer. If you care only about the first layer, add `.loader(page: 0)` to your pipeline. If you want to process each layer, see https://github.com/janko/image_processing/wiki/Splitting-a-PDF-into-multiple-images or use `.saver(allow_splitting: true)`.

I use carrierwave in my Ruby on Rails, but I didn't dive too deep to provide a reproducible script. But I can explain where the problem is:

Take a look here: https://github.com/janko/image_processing/blob/master/lib/image_processing/mini_magick.rb#L191

```ruby
        # When a multi-layer format is being converted into a single-layer
        # format, ImageMagick will create multiple images, one for each layer.
        # We want to warn the user that this is probably not what they wanted.
        def disallow_split_layers!(destination_path)
          layers = Dir[destination_path.sub(/\.\w+$/, '-*\0')]

          if layers.any?
            layers.each { |path| File.delete(path) }
            raise Error, "Source format is multi-layer, but destination format is single-layer. If you care only about the first layer, add `.loader(page: 0)` to your pipeline. If you want to process each layer, see https://github.com/janko/image_processing/wiki/Splitting-a-PDF-into-multiple-images or use `.saver(allow_splitting: true)`."
          end
        end
```

Let's assume we have `destination_path` without an extension, such as `/tmp/image_processing20200303-1-1ko9ubs.com-2020-binary-THUMBNAIL`. 
Then `destination_path.sub(/\.\w+$/, '-*\0')` replaces nothing and returns the original `destination_path`, so layers include itself: `["/tmp/image_processing20200303-1-1ko9ubs.com-2020-binary-THUMBNAIL"]`. Layers are removed and the exception raises.

**Comment by janko** [comment]
Thanks for the report. I’m curious, if the destination path doesn’t have an extension, how does ImageMagick now which format to convert to? Does it assume source format?

**Comment by Kukunin** [comment]
I don't use `image_processing` directly, it's used by `carrierwave`, so I don't know the answer. It just happened to me if I assign an image without an extension, it crashed with the exception, which makes no sense (since it's not about PDF). 
Maybe, after this bug is fixed, it will crash with a different error, that ImageMagick doesn't know the format without an ext.

**Comment by Kukunin** [comment]
We know the format of source image (magic bytes). If there is no extension, then we can assume, that the output format should be the same

**Comment by drusepth** [comment]
For the record, I also saw this error crop up all over production when a user uploaded a file with filename "Skiing E_ A. Poe. Mark S" for their avatar. Anywhere I called `.processed` on that avatar (for example, `user.avatar.variant(resize_to_limit: [size, size]).processed`) threw this error.

```
=> #<ActiveStorage::Blob id: 7619, key: "12bu4u9gmsmpgtd9ec68mt1ilkgr", filename: "Skiing E_ A. Poe. Mark S", content_type: "image/jpeg", metadata: {"identified"=>true, "width"=>520, "height"=>653, "analyzed"=>true}, byte_size: 38697, checksum: "Uc4Sr+sGTQ1p2bQQ2NCl1w==", created_at: "2020-04-03 01:43:41">
```

**Comment by gomachan46** [comment]
Hi,
I got same error, when filename included query parameter (e.g. hello.jpg?w=720).
This is often what happens when using CDN. (dynamic resizing, cropping, etc...)

I'm glad that no error occurs even if the filename has a query parameter.
