### ISSUE TITLE
Interest in an Imageflow backend?

### ISSUE THREAD

**Issue by lilith** [janko/image_processing#69]
Hi, I'm the author of [Imageflow](https://github.com/imazen/imageflow), and I was wondering if there would be interest in a contributed optional backend for it. 

I designed Imageflow from the ground up for this particular use case - low latency, safe server-side image processing. It's about 17x faster than ImageMagick and 2-3x faster than libvips for resizing large jpegs. It resizes images in 128-bit linear light and produces web-optimized files that are higher quality with much smaller file sizes. 

It supports webp, jpeg, png, and animated gifs.

**Comment by jeremy** [comment]
Wow, awesome project! For my part, I'd love to have access to Imageflow backend. 🙏🏼

**Comment by jcupitt** [comment]
Slight clarification: the 2 - 3x faster is just for jpeg, and just if you resize in linear light (libvips disables shrink on load in this case). If you don't resize in linear light, Imageflow and libvips are about the same speed. 

Perhaps you could say Imageflow gives you linear-light resizing of jpeg images for free? That might be fairer.

Imageflow is about 30% slower than libvips for png, both for linear light and for non-linear light, I think because it doesn't run decode and resize in parallel.

**Comment by lilith** [comment]
Linear light should be the only method ever used, as non-linear light destroys image highlights. When would non-linear light resizing have a valid use case?

**Comment by jcupitt** [comment]
But that's not what's being done here. image_processing does not do linear light downsampling.

An imageflow backend would not give a speed increase over the current backends, it would add linear light downsampling. It's misleading to talk about speed improvements.

Indeed, imageflow would *reduce* speed, if you consider formats other than jpeg.

**Comment by lilith** [comment]
I'm sorry, I'd assumed that linear light would be the default, given that both libvips and ImageMagick support it.

**Comment by janko** [comment]
Hi Lilith, sorry for not getting back to you before, it slipped off my radar. Yes, I think an Imageflow backend would be a good addition to this library, I had that in mind when I first built it. Here is a screenshot from my original blog post as proof 😛 

<img width="815" alt="Screenshot 2020-05-18 at 10 06 43" src="https://user-images.githubusercontent.com/795488/82189228-58a47500-98ef-11ea-937b-a046e36538ee.png">

I probably won't be able to help out much with the implementation unfortunately, as I'm focused on other open source projects at the moment. But I can definitely help with smaller things like setting up the test suite.

**Comment by janko** [comment]
Given that the ruby bindings are not ready to be used yet, I'm closing this issue for now.
