### ISSUE TITLE
Idea: instrumentation support

### ISSUE THREAD

**Issue by renchap** [janko/image_processing#70]
I am currently working on instrumenting various parts of my app (in my case to report to Datadog APM) and I would like to be able to have traces for image processing.
It would be very useful to have support for this in the library, so we can easily get timings and data about all image processing in our apps. Ideally it would have a basic (optional) logger implementation and access to the operation data (operation type, backend, timings, filename…).

**Comment by renchap** [comment]
I managed to monkey-patch ` ImageProcessing::Pipeline#call_processor` to instrument it, but it would be cleaner if there was an instrumentation API.
Here is how it looks for Datadog:

```ruby
module InstrumentImageProcessing
  def call_processor(**options)
    tags = {
      processor: processor.module_parent.name,
      operations: operations.map { |operation| operation[0] },
      source: source,
      destination: options[:destination],
    }

    Datadog.tracer.trace("image_processing.pipeline", span_type: "image_processing", tags: tags) do |_span|
      super(**options)
    end
  end
end

class ImageProcessing::Pipeline; prepend InstrumentImageProcessing; end

```

**Comment by janko** [comment]
This is an interesting idea, I'm open to it. I would definitely like monitoring to be easier.
