### ISSUE TITLE
Background Color When Converting Transparent PNG

### ISSUE THREAD

**Issue by rdetert** [janko/image_processing#71]
I'm coverting a transparent PNG to JPEG. By default, libvips uses black as the background color. I want to make the background white, instead.

Here is a thread on the libvips GitHub on how to do this: https://github.com/libvips/libvips/issues/1692

Here is what my code looks like:

```
ImageProcessing::Vips
  .source(file)
  .crop(*crop_points.split(CROP_POINT_DELIM).map(&:to_i))
  .convert('jpg')
  .saver(quality: 80)
  .resize_to_fill!(width.to_i, height.to_i)
```

**Comment by janko** [comment]
As suggested by John, you can use [`vips_flatten()`](https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-flatten):

```rb
ImageProcessing::Vips
  .source(file)
  .flatten(background: 255) # <=== set alpha color to white
  .crop(*crop_points.split(CROP_POINT_DELIM).map(&:to_i))
  .convert('jpg')
  .saver(quality: 80)
  .resize_to_fill!(width.to_i, height.to_i)
```

**Comment by rdetert** [comment]
Is there a way to do this conditionally? This produces strange results if I am converting from JPEG to JPEG.

**Comment by janko** [comment]
Sure, you can use `#custom` if you don't want to break the chaining flow:

```rb
ImageProcessing::Vips
  .source(file)
  .custom { |image| image.flatten(background: 255) if File.extname(file.path) == ".png" }
  .convert('jpg')
  .saver(quality: 80)
  .resize_to_fill!(width.to_i, height.to_i)
```

**Comment by rdetert** [comment]
This only works with PNGs that have transparency. Is there a way to test for transparency?

**Comment by janko** [comment]
Asking the image for `#has_alpha?` should do it:

```rb
ImageProcessing::Vips
  .source(file)
  .custom { |image| image.flatten(background: 255) if image.has_alpha? }
  .convert('jpg')
  .saver(quality: 80)
  .resize_to_fill!(width.to_i, height.to_i)
```

**Comment by rdetert** [comment]
This seems to work. Thanks!

**Comment by 9mm** [comment]
Do you know how I would format this for the rails conversion? I want to change black to white for png->jpg

```
    file.variant :square_medium,
      format: 'jpg',
      resize_to_fill: [600, 600],
      saver: { subsample_mode: 'on', strip: true, quality: 85 },
      composite: ['app/assets/images/watermark_square_medium.png', {
        gravity: 'south-west',
        offset: [10, 10]
      }]
```
