### ISSUE TITLE
Option to skip cropping on MiniMagick#resize_to_fill

### ISSUE THREAD

**Issue by etherbob** [janko/image_processing#74]
Would you be amenable to a pull request that adds a `crop: true`  parameter to `MiniMagick#resize_to_fill` that would then skip the cropping step when set to false?

We have a use case for calling resize("#{width}x#{height}^") and this seems like the logical place.

**Comment by janko** [comment]
Yes, that sounds reasonable 👍

**Comment by janko** [comment]
Added in https://github.com/janko/image_processing/pull/120.
