### ISSUE TITLE
Adding OpenCV support

### ISSUE THREAD

**Issue by janosrusiczki** [janko/image_processing#77]
Would it be possible to add OpenCV supoort (eg. via [ruby-opencv](https://github.com/ruby-opencv/ruby-opencv)) to the chain? Why? For example, to be able to center thumbnails on faces or objects in the image.

I was thinking if it would be possible to write something like:

```ruby
pipeline = ImageProcessing::MiniMagick.source(file)
```

... and then ...

```ruby
large     = pipeline.resize_to_limit!(800, 800)
thumbnail = pipeline.opencv(opencv_options).resize_to_limit!(300, 300)
```

I looked at the codebase, but at this point I'm not sure if the `.opencv` call would be able to pass down parameters to the `resize_to_limit!` call to specify a zone of interest in the image.

**Comment by janko** [comment]
You can do custom processing on the MiniMagick command instance, so you can hook OpenCV there:

```rb
ImageProcessing::MiniMagick.source(file)
  .custom do |magick|
    # calculate width & height and cropping parameters
    magick.crop("#{crop_w}x#{crop_h}+#{crop_x}+#{crop_y}")
    magick.resize("#{width}x#{height}>")
  end
```

I'm not familiar with OpenCV, so I cannot show you an example of an actual working command.
