### ISSUE TITLE
Convert SVG to transparent PNG using MiniMagick and Carrierwave 

### ISSUE THREAD

**Issue by jeremylynch** [janko/image_processing#80]
I am trying to use minimagick to convert a SVG to PNG with transparent background. Effectively, i want to run the following minimagick code:

```
convert test.png -transparent white transparent.png
```

I have tried the following and it's not working: 
```ruby
def convert_to_png
    minimagick! do |builder|
      builder = builder.density('1200')
      builder.resize "400x400"
      builder.background('none')
      builder.convert(:png)
      builder
  end
end
```

Could you please provide some guidance? Thanks!

**Comment by jeremylynch** [comment]
Any chance you could provide some guidance on this one @janko ?

**Comment by janko** [comment]
Notice that the MiniMagick options you're sending in Ruby don't match the ImageMagick command you want to build. So the following should generate the correct target ImageMagick command:

```rb
minimagick! do |builder|
  builder
    .transparent("white")
    .convert(:png)
end
```
