### ISSUE TITLE
Uploading HEIC images from Apple Photos/iPhone never works

### ISSUE THREAD

**Issue by k2director** [janko/image_processing#81]
Hi, first of all, thanks for creating this gem and your work on other projects like Shrine, which I'm expecting to try out in the next coupe of months!

As of now, I have a simple Active Storage file upload feature that lets you uploads JPGs and PDFs, and then displays thumbnail variants of them in the record's Show page. That all works thanks to Image Processing, but what doesn't work is if I try to upload an HEIC image from my Mac's Photos library, or from my iPhone. The upload works, actually, but when Rails goes to its Show page, and tries to display a variant for the uploaded image, it crashes with:

 "ActiveStorage::InvariableError in Invoices#show" 

....and it's crashing on this line in particular, which is trying to show the variant of the HEIC upload: 

 <%= link_to image_tag(image.variant(resize_to_limit: [100, nil])), image %>

I've upgraded my Image Processing gem to the latest version, as well as my ImageMagick install and then I tried installing the VIPS library (brew install vips) and placed "config.active_storage.variant_processor = :vips" in my Application.rb file. 

Any other idea of how to get this working? THANKS MUCH!

**Comment by janko** [comment]
A quick search in the Active Storage codebase for `ActiveStorage::InvariableError` shows that there is a predefined list of content types Active Storage will consider "variable", so you most likely just need to add the `image/heic` & `image/heif` content types to it:

> `config.active_storage.variable_content_types` accepts an array of strings indicating the content types that Active Storage can transform through ImageMagick. The default is `%w(image/png image/gif image/jpg image/jpeg image/pjpeg image/tiff image/bmp image/vnd.adobe.photoshop image/vnd.microsoft.icon image/webp)`

**Comment by k2director** [comment]
Janko, thank you for the quick response and for pointing that out! It was just what I needed to get things working, although I need to go a little deeper in my research next time!

Next stop: trying out Shrine!
