### ISSUE TITLE
Using New #mutate Block

### ISSUE THREAD

**Issue by metaskills** [janko/image_processing#82]
I was reading this news (https://libvips.github.io/libvips/2021/03/08/ruby-vips-mutate.html) about the new #mutate method with ruby-vips and was wondering if you had thoughts on leveraging that in Image Processing's pipelines?

**Comment by janko** [comment]
Every method defined on `Vips::Image` is available in ImageProcessing through method missing, the `#mutate` method should be usable as follows:

```rb
ImageProcessing::Vips.source(image)
  .mutate { |image| image.draw_circle!(...) }
  .call
```
