### ISSUE TITLE
Unexpected results with ruby-vips 2.1.0

### ISSUE THREAD

**Issue by benubois** [janko/image_processing#84]
Hi,

Thanks for image_processing!

I noticed some unusual color issues after updating to `ruby-vips 2.1.0` on some images. Passing `sharpen: false` prevents the issue.

This is on Ubuntu 20.04 with `libvips42/focal,now 8.9.1-2 amd64` (the default version that gets installed with `apt install libvips`). FWIW I did not see this issue when running the same code locally on a Mac.

```ruby
require "bundler/inline"
require "securerandom"

gemfile do
  source "https://rubygems.org"
  gem "ruby-vips", "= 2.1.0"
  gem "image_processing"
  gem "down"
end

original = Down.download("https://i.ytimg.com/vi/1pZPIylDqMk/maxresdefault.jpg")

path_one = File.join(Dir.tmpdir, "#{SecureRandom.hex}.jpg")
path_two = File.join(Dir.tmpdir, "#{SecureRandom.hex}.jpg")

ImageProcessing::Vips
  .source(original)
  .resize_to_fill(600, 400)
  .call(destination: path_one)

ImageProcessing::Vips
  .source(original)
  .resize_to_fill(600, 400, sharpen: false)
  .call(destination: path_two)

puts path_one
puts path_two
```

without sharpen:

![d338294a0b8b69b526f1cd7ffcdd9a9a](https://user-images.githubusercontent.com/133809/112089767-84b40680-8b4f-11eb-954c-b7c1437c4024.jpg)

with sharpen:

![7367ad6eb530dbc649c34d9d45361bf2](https://user-images.githubusercontent.com/133809/112089749-7960db00-8b4f-11eb-92d3-1b0847e54ef4.jpg)

**Comment by janko** [comment]
Thanks for the report, that seems awful, I will probably need to turn off automatic sharpening then.

**Comment by maxence33** [comment]
Just a guess but wouldn't this be related to https://github.com/janko/image_processing/issues/83 which also raises an issue with sharpening with ruby-vips 2.1.0 ?

**Comment by benubois** [comment]
Yes, this does seem to be related to #83. From the [follow up issue](https://github.com/libvips/ruby-vips/issues/291) it turned out that `ruby-vips 2.1.0` is low-key incompatible with `libvips 8.9.1` specifically ([for now](https://github.com/libvips/ruby-vips/issues/291#issuecomment-801020368)). Anyway compiling `libvips 8.10.5` from source does fix this issue. 

I think the easiest thing for `image_processing` to do (if anything) would be to pin `"ruby-vips",  "< 2.1.0"` until `ruby-vips 2.1.x + libvips 8.9.1` works.

**Comment by jcupitt** [comment]
Hello, there's now ruby-vips 2.1.2 with a fix for this issue. Sorry for the breakage.

**Comment by janko** [comment]
Great, thank you, closing this one then 🤘🏻
