### ISSUE TITLE
Vips::Error: No known saver for '/tmp/image_processing20210614-4-bh3rbt.jfif'

### ISSUE THREAD

**Issue by andresespinosapc** [janko/image_processing#86]
I'm getting this error when trying to apply any operation over a file with the extension `.jfif`. It should be solved just by changing the extension to `jpg`, but it should be handled by this library or ruby-vips or libvips, I'm not sure where the error is coming from.

**Comment by janko** [comment]
If you don't specify the output extension, this library assumes you want to keep the same one. For libvips it should theoretically be possible to detect whether the input format is supported for the output (libvips has sufficient introspection capabilities for that), but I wouldn't want to assume what the output extension should be.

**Comment by andresespinosapc** [comment]
And is there a method to get the input extension? Or I'd have to parse it from the file path?

**Comment by janko** [comment]
Better to parse it from the file path using `File.extname`. I don't think I would feel comfortable doing automatic format conversion in ImageProcessing, I'd rather that the user is forced to decide.
