### ISSUE TITLE
Problem with stripping images

### ISSUE THREAD

**Issue by zorar4ik** [janko/image_processing#87]
Greetings. I am trying to migrate from `imagemagick` to `libvips` and I faced a bit odd issue when try to strip some images.

Environment:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

Ruby version ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
Vips version 8.9.1-Sun Feb 23 08:51:26 UTC 2020
ruby-vips version 2.1.2 (also tried on 2.0.17)
image_processing 1.12.1
```
```
require 'vips'

file = File.new('~/Downloads/portrait_5.jpg')

builder = ImageProcessing::Vips.source(file).saver(quality: 10, strip: true)
builder.call
```

![portrait_5](https://user-images.githubusercontent.com/22009908/126795069-bb0b3208-e481-4daf-9405-5ecb20428abb.jpg)

And it breaks somewhere here: 
```
(rails:28418): GLib-GObject-CRITICAL **: 13:27:12.286: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
/usr/local/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby-vips-2.1.2/lib/vips/operation.rb:211: [BUG] Segmentation fault at 0x00000000000000c8
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0049 p:---- s:0306 e:000305 CFUNC  :vips_cache_operation_build
c:0048 p:0012 s:0301 e:000300 METHOD /usr/local/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby-vips-2.1.2/lib/vips/operation.rb:211
c:0047 p:0363 s:0296 E:000a78 METHOD /usr/local/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby-vips-2.1.2/lib/vips/operation.rb:469
c:0046 p:0027 s:0275 e:000274 METHOD /usr/local/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ruby-vips-2.1.2/lib/vips/image.rb:229
c:0045 p:0137 s:0268 e:000267 METHOD /usr/local/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/image_processing-1.12.1/lib/image_processing/vips.rb:44
c:0044 p:0094 s:0257 e:000256 METHOD /usr/local/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/image_processing-1.12.1/lib/image_processing/processor.rb:15
c:0043 p:0034 s:0246 e:000245 METHOD /usr/local/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/image_processing-1.12.1/lib/image_processing/pipeline.rb:50
```

However when I do it directly with `ruby-vips` it works.
```
require 'vips'

file = File.new('~/Downloads/portrait_5.jpg')

image = Vips::Image.new_from_file(file.path)
image.write_to_file '/workspace/spec/sample.jpg', Q: 10, strip: true
```

And it seems to work fine.
![sample](https://user-images.githubusercontent.com/22009908/126795067-047b75a9-65fe-4aea-948f-08921b9cfc5b.jpg)

Can you guide me what I am doing wrong? Thanks in advance

**Comment by janko** [comment]
Thanks for the report. Could you attach that image here, so that I can reproduce more easily?

**Comment by zorar4ik** [comment]
I thought I did it on my previous message. Here is it.
PS. thanks for fast response
![portrait_5](https://user-images.githubusercontent.com/22009908/126829662-2819f7be-4283-45b9-a7b8-f563f802aad5.jpg)

**Comment by zorar4ik** [comment]
I have tested images with different EXIF orientation tags and discovered that:
EXIF 1, 3, 6, 8 values WORKS without any errors.
EXIF 2, 4, 5, 7 DOES NOT WORK, producing error that I have written above.

Still saving directly via `Vips::Image.write_to_file` method works on every image despite on `exif-ifd0-Orientation` tag value

**Comment by renchap** [comment]
This is a known behaviour in libvips < 8.10. What libvips version are you using?

Mirrored EXIF orientations (2, 4, 5, 7) have been implemented in this PR: https://github.com/libvips/libvips/pull/1650

**Comment by zorar4ik** [comment]
@renchap hi, thanks for info. I am on 8.9.1 version. I'll try to build the latest stable version of `libvips`.

**Comment by janko** [comment]
The reason you're encountering this issue with ImageProcessing is because it performs autorotation by default, which vanilla ruby-vips does not. The alternative would be to disable autorotation, I think it's a `loader` option.

**Comment by zorar4ik** [comment]
Thanks for info @janko!

**Comment by zorar4ik** [comment]
@janko, a little update, I installed latest version of `libvips (vips-8.11.2-Sat Jul  3 10:17:33 UTC 2021)` and it seems it solved the issue, I don't need to disable rotation at all. Thanks for your support.
