### ISSUE TITLE
How can I adjust individual levels using ::Vips?

### ISSUE THREAD

**Issue by rafaelmagu** [janko/image_processing#94]
Hey there, thank you for creating such a useful gem. I'm employing it on a personal project and it helps a lot.

Disclaimer: I'm a novice when it comes to image processing, and while I've been trying to read and comprehend the existing open (and closed) issues in this repo, I haven't yet found a good example that tackles what I'm trying to do.

On my personal project, I have a list of filters that I can apply to uploaded images to ActiveStorage. Each filter is defined as a helper method. I took inspiration from [this list of filters](https://gist.github.com/tonycoco/2910540), and have modified them to suit this gem. However, I'd like to move away from MiniMagick and towards libvips, and I've been struggling to convert some of the helpers.

How can I replicate the below helper using `ImageProcessing::Vips`? Specifically, the `.channel` and `.level` calls, given libvips doesn't have those.

```ruby
def filter_lomo(img)
  ImageProcessing::MiniMagick
    .source(img)
    .resize_to_fit(1024, 1024)
    .convert('jpeg')
    .channel('R').level('22%')
    .channel('G').level('22%')
    .saver(strip: true)
    .call
end
```

I also realise this might not be the best forum to ask this question, so I'll gladly accept some guidance as to where best to ask this question.

**Comment by janko** [comment]
Questions about converting ImageMagick commands into libvips commands are best asked on [libvips discussions](https://github.com/libvips/libvips/discussions). The author of libvips is also the author of ruby-vips, so you'll have no problems talking in terms of ruby code.

**Comment by jcupitt** [comment]
Hello all, asked and answered here: https://github.com/libvips/libvips/discussions/2447

For this specific question, just write;

```ruby
image *= [1.22, 1.22, 1]
```

**Comment by rafaelmagu** [comment]
Thank you @jcupitt and @janko for the quick responses. Just so I'm clear: this type of adjustment isn't something that's available through the chainable API for `ImageProcessing::Vips`, is it?

**Comment by janko** [comment]
ImageProcessing gives you an escape hatch, where you can call methods on a `Vips::Image` object directly:

```rb
ImageProcessing::Vips
    .source(img)
    .resize_to_fit(1024, 1024)
    .convert('jpeg')
    .custom { |image| image * [1.22, 1.22, 1] }
    .saver(strip: true)
    .call
```

**Comment by rafaelmagu** [comment]
Oh that's brilliant, thanks!
